site_name: 'Kovenant'
site_url: 'http://kovenant.mplatvoet.nl'
site_description: 'Kovenant. Promises for Kotlin.'
site_author: 'Mark Platvoet'
copyright: '2015'

repo_url: https://github.com/mplatvoet/kovenant
repo_name: 'GitHub'

pages:
- ['index.md', 'Home']
- ['api/async.md', 'API Documentation', 'Async']
- ['api/deferred.md', 'API Documentation', 'Deferred']
- ['api/callbacks.md', 'API Documentation', 'Callbacks']
- ['api/then.md', 'API Documentation', 'Then']
- ['api/combine.md', 'API Documentation', 'Combine']
- ['api/configuration.md', 'API Documentation', 'Configuration']
- ['api/context.md', 'API Documentation', 'Context']
- ['api/interopJvm.md', 'API Documentation', 'Executors (JVM)']
- ['android/features.md', 'Android','Features']
- ['android/config.md', 'Android','Configuring']
- ['goals.md', 'Goals']
- ['performance.md', 'Misc', 'Performance']
- ['considerations.md','Misc', 'Considerations']

#theme: bootstrap
theme_dir: theme/yeti