site_name: 'Kovenant'
site_url: 'http://kovenant.komponents.nl'
site_description: 'Kovenant. Promises for Kotlin.'
site_author: 'Mark Platvoet'
copyright: '2015'

repo_url: https://github.com/mplatvoet/kovenant
repo_name: 'GitHub'

pages:
- Home: 'index.md'
- API Documentation:
    - 'Core Usage': 'api/core_usage.md'
    - 'Core Configuration': 'api/core_config.md'
    - 'Combine': 'api/combine_usage.md'
    - 'Functional': 'api/functional_usage.md'
    - 'JVM Specific': 'api/jvm_usage.md'
    - 'Testing': 'api/test_usage.md'
- Android:
    - 'Features': 'android/features.md'
    - 'Configuring': 'android/config.md'
- Addons:
    - 'UI': 'addons/ui.md'
    - 'Disruptor': 'addons/disruptor.md'
    - 'Progress': 'addons/progress.md'
- Misc:
    - 'Goals': 'misc/goals.md'
    - 'Performance': 'misc/performance.md'
    - 'Considerations': 'misc/considerations.md'
- Changelog:
    - 'Released': 'changelog.md'
    - 'Roadmap': 'roadmap.md'

theme: yeti